# Generated by Django 5.1.5 on 2025-03-21 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usuario',
            new_name='usuarios',
        ),
    ]
