# Generated by Django 5.1.5 on 2025-03-21 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_rename_usuario_usuarios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usuarios',
            new_name='usuario',
        ),
    ]
