# Generated by Django 5.1.5 on 2025-03-21 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usuario',
            new_name='cadastrar_novo_usuario',
        ),
        migrations.RenameField(
            model_name='cadastrar_novo_usuario',
            old_name='id_usuario',
            new_name='id',
        ),
    ]
