# Generated by Django 5.1.5 on 2025-03-21 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_rename_usuario_cadastrar_novo_usuario_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cadastrar_novo_usuario',
            new_name='Usuario',
        ),
    ]
